FROM python:3.12-slim

WORKDIR /opt/dagster/app

# system deps
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
 && rm -rf /var/lib/apt/lists/*

# Install dagster + your deps
RUN pip install --no-cache-dir \
    dagster \
    dagit \
    dagster-dbt \
    dbt-postgres \
    boto3 \
    pandas \
    pyarrow \
    psycopg2-binary\
    webcolors\
    s3fs


# expose Dagit UI port
EXPOSE 3000

# default command
CMD ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000"]