version: "3.9"
services:
  # S3 imitation with MinIO
  minio:
    container_name: minio_used_vehicles
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    ports:
      - "9120:9000"  # S3 API
      - "9121:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_used_vehicles:/data

  # Jupyter Notebook for data analysis
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter_used_vehicles
    user: "1000:100"
    ports:
      - "8889:8888"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - "C:/projects_github/used_cars_dbt_project/notebooks:/home/jovyan/work:rw"
    working_dir: /home/jovyan/work
    command: 
      - /bin/bash
      - -c
      - |
        pip install --no-cache-dir \
          s3fs==2024.3.1 \
          aiobotocore==2.12.3 \
          boto3==1.34.69 \
          botocore==1.34.69 \
          pyarrow \
          fastparquet \
        && start-notebook.py \
          --ServerApp.root_dir=/home/jovyan/work \
          --IdentityProvider.token='' \
          --ServerApp.password=''   
    depends_on:
      - minio

  # Main business DB
  postgres:
    image: postgres:15
    container_name: postgres_used_vehicles
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: used_vehicles_ads
    volumes:
      - postgres_used_vehicles:/var/lib/postgresql/data

volumes:
  minio_used_vehicles:
  postgres_used_vehicles: